// Code generated by Kitex v0.7.2. DO NOT EDIT.

package projectservice

import (
	server "github.com/cloudwego/kitex/server"
	notify "github.com/li1553770945/personal-notify-service/kitex_gen/notify"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler notify.ProjectService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
