// Code generated by Kitex v0.7.2. DO NOT EDIT.

package projectservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	notify "github.com/li1553770945/personal-notify-service/kitex_gen/notify"
)

func serviceInfo() *kitex.ServiceInfo {
	return projectServiceServiceInfo
}

var projectServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ProjectService"
	handlerType := (*notify.ProjectService)(nil)
	methods := map[string]kitex.MethodInfo{
		"SendNotify": kitex.NewMethodInfo(sendNotifyHandler, newProjectServiceSendNotifyArgs, newProjectServiceSendNotifyResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":     "notify",
		"ServiceFilePath": `idl/notify.thrift`,
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.7.2",
		Extra:           extra,
	}
	return svcInfo
}

func sendNotifyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notify.ProjectServiceSendNotifyArgs)
	realResult := result.(*notify.ProjectServiceSendNotifyResult)
	success, err := handler.(notify.ProjectService).SendNotify(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProjectServiceSendNotifyArgs() interface{} {
	return notify.NewProjectServiceSendNotifyArgs()
}

func newProjectServiceSendNotifyResult() interface{} {
	return notify.NewProjectServiceSendNotifyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendNotify(ctx context.Context, req *notify.SendNotifyReq) (r *notify.SendNotifyResp, err error) {
	var _args notify.ProjectServiceSendNotifyArgs
	_args.Req = req
	var _result notify.ProjectServiceSendNotifyResult
	if err = p.c.Call(ctx, "SendNotify", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
